apiVersion: v1
kind: Namespace
metadata:
  name: att-arma-bot
---
apiVersion: v1
kind: Secret
metadata:
  name: serenity-arma-secrets
  namespace: att-arma-bot
type: Opaque
data:
  discord_api_token: BASE64_ENCODED_TOKEN # replace with token base64-encoded with `echo -n 'your_discord_bot_token' | base64`
  steam_api_key: BASE64_ENCODED_STEAM_API_KEY # replace with steam api key base64-encoded with `echo -n 'your_steam_api_key' | base64`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: serenity-arma-deployment
  namespace: att-arma-bot
  labels:
    app: serenity-arma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serenity-arma
  template:
    metadata:
      labels:
        app: serenity-arma
    spec:
      containers:
        - name: serenity-arma
          image: your.registry.com/serenity-arma:latest
          imagePullPolicy: Always
          env:
            - name: ARMA_HOST_STRING
              value: "12.34.56.78:2302" # replace with your arma server ip and port
            - name: GUILD_ID
              value: "123456789012345678" # replace with your discord guild id
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: serenity-arma-secrets
                  key: discord_api_token
            - name: STEAM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: serenity-arma-secrets
                  key: steam_api_key